---
  - name: launch vm2
    openstack.cloud.server:
      state: present
      cloud: chameleon
      name: team18_vm2
      availability_zone: nova
      image: CC-Ubuntu18.04-20200922
      key_name: Chameleon_key
      timeout: 300
      flavor: m1.small
      network: 4b484898-92b4-4a4b-9c5d-7d55bd72f1ee
      security_groups: 7e09e9fd-4971-49bb-bd55-9aa2fa149b16
      floating_ips:
        - 129.114.26.223

  - name: launch vm3
    openstack.cloud.server:
      state: present
      cloud: chameleon
      name: team18_vm3
      availability_zone: nova
      image: CC-Ubuntu18.04-20200922
      key_name: Chameleon_key
      timeout: 300
      flavor: m1.small
      network: 4b484898-92b4-4a4b-9c5d-7d55bd72f1ee
      security_groups: 7e09e9fd-4971-49bb-bd55-9aa2fa149b16
      floating_ips:
        - 129.114.27.82
...