#version: '2'
#services:
#  kafka4:
#    image: wurstmeister/kafka
#    ports:
#      - "9095:9092"
#    environment:
#      KAFKA_LOG_DIRS: /kafka
#      KAFKA_BROKER_ID: 4
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://129.114.26.55:9092
#      KAFKA_LISTENERS: PLAINTEXT://:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
#      KAFKA_LOG_RETENTION_HOURS: "168"
#      KAFKA_LOG_RETENTION_BYTES: "100000000"
#      KAFKA_ZOOKEEPER_CONNECT:  129.114.27.112:2181

#  kafka5:
#    image: wurstmeister/kafka
#    ports:
#      - "9096:9092"
#    environment:
#      KAFKA_LOG_DIRS: /kafka
#      KAFKA_BROKER_ID: 5
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://129.114.27.82:9092
#      KAFKA_LISTENERS: PLAINTEXT://:9092
#      KAFKA_LOG_RETENTION_HOURS: "168"
#      KAFKA_LOG_RETENTION_BYTES: "100000000"
#      KAFKA_ZOOKEEPER_CONNECT:  129.114.27.112:2181

version: '2'
services:
  couchdb:
    image: docker.io/bitnami/couchdb:3-debian-10
    environment:
      - COUCHDB_PASSWORD=couchdb
    ports:
      - '5984:5984'
      - '4369:4369'
      - '9100:9100'
    volumes:
      - couchdb_data:/bitnami/couchdb
volumes:
  couchdb_data:
    driver: local
